spring:
  profiles:
    active: mysql
  datasource:
    continue-on-error: true

endpoints:
  cors:
    allowed-origins: http://localhost:4200

logging:
  file: logs/iot.log

web:
  signing-key: appletree